version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "@types/node"
        versions: ["14.x"]
