version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    automerged_updates:
      - match:
        dependency_type: "all"
        update_type: "all"
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
    automerged_updates:
      - match:
        dependency_type: "all"
        update_type: "all"
    ignore:
      - dependency-name: "@types/node"
        versions: ["14.x"]
