[package]
name = "bast"
version = "0.1.0"
authors = ["Alexandre Chêne <kooparse@protonmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1"
actix-cors = "0.1"
diesel = { version="1.4.2", features = ["postgres", "r2d2"] }
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
futures = "0.1"
bcrypt = "0.6"
jsonwebtoken = "6.0"
env_logger = "0.7"
