[package]
name = "bast"
version = "0.1.0"
authors = ["Alexandre Chêne <kooparse@protonmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.8"
diesel = { version="1.4.2", features = ["postgres", "r2d2"] }
dotenv = "0.15"
